package domain.exception;

public class WrongNumberException extends Exception {

	public WrongNumberException() {
		super();
		// TODO 自動生成されたコンストラクター・スタブ
	}

	public WrongNumberException(String message, Throwable cause, boolean enableSuppression,
			boolean writableStackTrace) {
		super(message, cause, enableSuppression, writableStackTrace);
		// TODO 自動生成されたコンストラクター・スタブ
	}

	public WrongNumberException(String message, Throwable cause) {
		super(message, cause);
		// TODO 自動生成されたコンストラクター・スタブ
	}

	public WrongNumberException(String message) {
		super(message);
		// TODO 自動生成されたコンストラクター・スタブ
	}

	public WrongNumberException(Throwable cause) {
		super(cause);
		// TODO 自動生成されたコンストラクター・スタブ
	}

}
